// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyA7lCsRLi6_UqHbX-fWPaFNN93m5YKrzVQ',
    appId: '1:390024911936:web:5f4ce92d8124ad115153a5',
    messagingSenderId: '390024911936',
    projectId: 'lost-and-found-v2-7e553',
    authDomain: 'lost-and-found-v2-7e553.firebaseapp.com',
    storageBucket: 'lost-and-found-v2-7e553.firebasestorage.app',
    measurementId: 'G-MEASUREMENT',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyA7lCsRLi6_UqHbX-fWPaFNN93m5YKrzVQ',
    appId: '1:390024911936:android:5f4ce92d8124ad115153a5',
    messagingSenderId: '390024911936',
    projectId: 'lost-and-found-v2-7e553',
    storageBucket: 'lost-and-found-v2-7e553.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyA7lCsRLi6_UqHbX-fWPaFNN93m5YKrzVQ',
    appId: '1:390024911936:ios:5f4ce92d8124ad115153a5',
    messagingSenderId: '390024911936',
    projectId: 'lost-and-found-v2-7e553',
    storageBucket: 'lost-and-found-v2-7e553.firebasestorage.app',
    iosBundleId: 'com.example.lostAndFound',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyA7lCsRLi6_UqHbX-fWPaFNN93m5YKrzVQ',
    appId: '1:390024911936:ios:5f4ce92d8124ad115153a5',
    messagingSenderId: '390024911936',
    projectId: 'lost-and-found-v2-7e553',
    storageBucket: 'lost-and-found-v2-7e553.firebasestorage.app',
    iosBundleId: 'com.example.lostAndFound',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyA7lCsRLi6_UqHbX-fWPaFNN93m5YKrzVQ',
    appId: '1:390024911936:web:5f4ce92d8124ad115153a5',
    messagingSenderId: '390024911936',
    projectId: 'lost-and-found-v2-7e553',
    authDomain: 'lost-and-found-v2-7e553.firebaseapp.com',
    storageBucket: 'lost-and-found-v2-7e553.firebasestorage.app',
    measurementId: 'G-MEASUREMENT',
  );
}
